<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>p6</string>
		<string>pl</string>
		<string>pl6</string>
		<string>pm</string>
		<string>pm6</string>
		<string>t</string>
		<string>nqp</string>
	</array>
	<key>firstLineMatch</key>
	<string>(^#!.*\bperl6\b)|use\s+v6</string>
	<key>keyEquivalent</key>
	<string>^~P</string>
	<key>name</key>
	<string>Perl 6</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^=begin</string>
			<key>end</key>
			<string>^=end</string>
			<key>name</key>
			<string>comment.block.perl6</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.line.number-sign.perl6</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.perl6</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.perl6</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.perl6</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\['\\]</string>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.perl6</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.perl6</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.perl6</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\[abtnfre"\\]</string>
					<key>name</key>
					<string>constant.character.escape.perl6</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\$\w+\b</string>
			<key>name</key>
			<string>variable.other.perl6</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>token\s+{</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>string.regexp.grammar.token.perl6</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:\b|\B(?&lt;=[-']))(?&lt;!(?:ACHTUNG|ATTN|ATTENTION|FIXME|NB|TODO|TBD|WTF|XXX|NOTE))(?:\b|[-']\B\@=\))</string>
			<key>name</key>
			<string>markup.bold.attention.perl6</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(macro|sub|submethod|method|multi|proto|only|rule|token|regex|category)\b</string>
			<key>name</key>
			<string>storage.type.declare.routine.perl6</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(module|class|role|package|enum|grammar|slang|subset)\b</string>
			<key>name</key>
			<string>keyword.other.module.perl6</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(self)\b</string>
			<key>name</key>
			<string>variable.language.perl6</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(use|require)\b</string>
			<key>name</key>
			<string>keyword.other.include.perl6</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|else|elsif|unless)\b</string>
			<key>name</key>
			<string>keyword.control.conditional.perl6</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(let|my|our|state|temp|has|constant)\b</string>
			<key>name</key>
			<string>storage.type.variable.perl6</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(for|loop|repeat|while|until|gather|given)\b</string>
			<key>name</key>
			<string>keyword.control.repeat.perl6</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(take|do|when|next|last|redo|return|contend|maybe|defer|default|exit|make|continue|break|goto|leave|async|lift)\b</string>
			<key>name</key>
			<string>keyword.control.flowcontrol.perl6</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(is|as|but|trusts|of|returns|handles|where|augment|supersede)\b</string>
			<key>name</key>
			<string>storage.modifier.type.constraints.perl6</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(BEGIN|CHECK|INIT|START|FIRST|ENTER|LEAVE|KEEP|UNDO|NEXT|LAST|PRE|POST|END|CATCH|CONTROL|TEMP)\b</string>
			<key>name</key>
			<string>meta.function.perl6</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(die|fail|try|warn)\b</string>
			<key>name</key>
			<string>keyword.control.control-handlers.perl6</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(prec|irs|ofs|ors|export|deep|binary|unary|reparsed|rw|parsed|cached|readonly|defequiv|will|ref|copy|inline|tighter|looser|equiv|assoc|required)\b</string>
			<key>name</key>
			<string>storage.modifier.perl6</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(NaN|Inf)\b</string>
			<key>name</key>
			<string>constant.numeric.perl6</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(oo|fatal)\b</string>
			<key>name</key>
			<string>keyword.other.pragma.perl6</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Object|Any|Junction|Whatever|Capture|MatchSignature|Proxy|Matcher|Package|Module|ClassGrammar|Scalar|Array|Hash|KeyHash|KeySet|KeyBagPair|List|Seq|Range|Set|Bag|Mapping|Void|UndefFailure|Exception|Code|Block|Routine|Sub|MacroMethod|Submethod|Regex|Str|str|Blob|Char|ByteCodepoint|Grapheme|StrPos|StrLen|Version|NumComplex|num|complex|Bit|bit|bool|True|FalseIncreasing|Decreasing|Ordered|Callable|AnyCharPositional|Associative|Ordering|KeyExtractorComparator|OrderingPair|IO|KitchenSink|RoleInt|int|int1|int2|int4|int8|int16|int32|int64Rat|rat|rat1|rat2|rat4|rat8|rat16|rat32|rat64Buf|buf|buf1|buf2|buf4|buf8|buf16|buf32|buf64UInt|uint|uint1|uint2|uint4|uint8|uint16|uint32uint64|Abstraction|utf8|utf16|utf32)\b</string>
			<key>name</key>
			<string>support.type.perl6</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(div|x|xx|mod|also|leg|cmp|before|after|eq|ne|le|lt|gt|ge|eqv|ff|fff|and|andthen|Z|X|or|xor|orelse|extra|m|mm|rx|s|tr)\b</string>
			<key>name</key>
			<string>keyword.operator.perl6</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>escaped_char</key>
		<dict>
			<key>match</key>
			<string>\\.</string>
			<key>name</key>
			<string>constant.character.escape</string>
		</dict>
		<key>variable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\$\{)(?:[a-zA-Zx7f-xff\$]|::)(?:[a-zA-Z0-9_x7f-xff\$]|::)*(\})</string>
					<key>name</key>
					<string>variable.other.readwrite.global</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.perl6</string>
	<key>uuid</key>
	<string>E685440C-0E20-4424-9693-864D5240A269</string>
</dict>
</plist>
